groups:
  - name: OrganizationMetrics
    rules:
      - alert: OrganiationAlert
        expr: organization_alert{job="event_exporter"} == 1
        for: 1m
        annotations:
          summary: "Organization {{$labels.organization}}"