global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: materialize
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'materialized:6875'
  - job_name: event_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'consumer:80'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]